{% set name = "langchain-qdrant" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/langchain_qdrant-{{ version }}.tar.gz
  sha256: 6ac4567b387ed2a94465d3039080e82ec031bf605b215045c148032c2ebce4b7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pdm-backend
    - pip
  run:
    - python >={{ python_min }},<4.0
    - pydantic >=2.7.4,<3.0.0
    - langchain-core >=1.0.0,<2.0.0
    - qdrant-client >=1.10.1,<2.0.0

test:
  imports:
    - langchain_qdrant
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/langchain-ai/langchain
  summary: An integration package connecting Qdrant and LangChain
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
